name = "api"
main = "src/index.ts"
compatibility_date = "2024-11-06"

compatibility_flags = [ "nodejs_compat" ]

# route = { pattern = "", custom_domain = true }

[vars]
JWT_SECRET="xxxx" 
APP_DOMAIN="{MY_APP_DOMAIN}"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Please remove comment if you want to use D1
# [[d1_databases]]
# binding = "DB"
# database_name = "my-db"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1